# Generated by Django 3.0.5 on 2020-05-02 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roadmaps', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='roadmaps.Tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_networks',
            field=models.ManyToManyField(blank=True, to='account.SocialNetwork'),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.ManyToManyField(blank=True, related_name='state_profile', to='account.Location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
