# Generated by Django 3.0.5 on 2020-05-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200502_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, related_name='country_profile', to='account.Location'),
        ),
    ]
