# Generated by Django 3.0.5 on 2020-05-04 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200502_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='cv',
            new_name='facebook_profile',
        ),
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='facebook',
            new_name='personal_site',
        ),
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='github',
            new_name='stackoverflow_profile',
        ),
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='instagram',
            new_name='youtube_channel',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='youtube',
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='github_profile',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='instagram_username',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='linkedin_profile',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='reddit_username',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='telegram_username',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='twitter_username',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='whatsapp_number',
            field=models.IntegerField(blank=True, db_index=True, max_length=15, null=True),
        ),
    ]
