# Generated by Django 3.0.5 on 2020-05-04 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200504_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='whatsapp_number',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MaxLengthValidator(15)]),
        ),
    ]
