# Generated by Django 3.0.5 on 2020-05-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200504_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='show_email',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
    ]
