# Generated by Django 3.0.5 on 2020-05-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
        migrations.RenameField(
            model_name='history',
            old_name='accounts',
            new_name='account',
        ),
    ]
