# Generated by Django 3.0.5 on 2020-05-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_socialnetwork_show_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='github_profile',
            field=models.URLField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
