# Generated by Django 3.0.5 on 2020-05-04 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200504_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_networks',
        ),
        migrations.AddField(
            model_name='profile',
            name='social_networks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.SocialNetwork'),
        ),
    ]
