# Generated by Django 3.0.5 on 2020-05-05 05:10

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200504_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
