# Generated by Django 3.0.5 on 2020-05-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200505_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/logo.png', null=True, upload_to='profile_pics'),
        ),
    ]
