# Generated by Django 3.0.5 on 2020-05-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200505_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='images/logo.png', upload_to='profile_pics'),
        ),
    ]
