# Generated by Django 3.0.5 on 2020-04-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='roadmaps',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='topics',
            field=models.ManyToManyField(to='roadmaps.Topic'),
        ),
    ]
