# Generated by Django 3.0.5 on 2020-04-13 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_auto_20200413_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadmap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
