# Generated by Django 3.0.5 on 2020-04-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0003_auto_20200413_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='image',
            field=models.ImageField(blank=True, upload_to='roadmap_images'),
        ),
    ]
