# Generated by Django 3.0.5 on 2020-04-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0006_auto_20200415_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='place',
            field=models.IntegerField(null=True),
        ),
    ]
