# Generated by Django 3.0.5 on 2020-04-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0007_unit_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='place',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
