# Generated by Django 3.0.5 on 2020-04-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0008_auto_20200415_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='about',
            new_name='objectives',
        ),
    ]
