# Generated by Django 3.0.5 on 2020-04-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0009_auto_20200415_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
