# Generated by Django 3.0.5 on 2020-04-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0011_auto_20200416_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='place',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unit',
            name='place',
            field=models.IntegerField(default=1),
        ),
    ]
